### ISSUE TITLE
Produce a summary table for each data type

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-actions/dataset-report#22]
From @wjchulme, via [this Slack thread][1]. Thanks, Will 🙂 

At present, dataset-report produces a summary table for all data types. However, it should produce a summary table for each data type. The columns in these summary tables would depend upon the data types. The [`skimr`][2] R package does this; Will has shared [an example output][3].

> I like this format because it's one line per column, so it's very easy to skim info rather than wading through half a screen's worth of information for each column. ...
> But what skimr also does is split up columns by type which makes it easier to report type-specific info in that format.

[1]: https://bennettoxford.slack.com/archives/C02HJTL065A/p1652970836368469
[2]: https://cran.r-project.org/web/packages/skimr/index.html
[3]: https://gist.github.com/wjchulme/c630cee4197d65b441c4c3f3f670efcf

**Comment by iaindillingham** [comment]
Do we want a summary table for each data type? We encode boolean variables as `bool` (`False`/`True`) but also as `int` (`0`/`1`). It's important to distinguish between `int`-as-boolean and `int`-as-integer, though: we'd summarize them differently. Similarly, we encode categories as `str` (`object`) but also as `CategoricalDtype` ([similar to R's `factor`][1]). In this case, however, we'd summarize them in the same way.

Perhaps we want a summary table for each [level of measurement][2]? Perhaps we can simplify the levels of measurement to discrete and continuous?

[1]: https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#differences-to-r-s-factor
[2]: https://en.wikipedia.org/wiki/Level_of_measurement

**Comment by iaindillingham** [comment]
I'd like to check what a summary table for boolean variables might look like. To recap, we encode boolean variables as `False`/`True` but also as `0`/`1`.[^1] At present, each boolean variable has its own table. This table shows counts/percentages for the values that are present: if only `0`s are present, then only counts/percentages for `0` are shown. For example:

![Screenshot 2022-05-31 at 17-25-19 Dataset Report](https://user-images.githubusercontent.com/477263/171225448-0e3716fc-4d07-4c66-a565-f5d7a66577a4.png)

Similarly, if `0`s and `1`s are present, then counts/percentages for `0` and `1` are shown. For example:

![Screenshot 2022-05-31 at 17-26-31 Dataset Report](https://user-images.githubusercontent.com/477263/171225509-21534e4c-86c9-434c-842c-52e0a01e5996.png)

We could say that the domain is _internal_ to the table.

With a summary table for boolean variables -- _à la_ `skimr` -- each boolean variable has its own row. We might expect a column for counts/percentages of false values, such as `0` or `False`; and a column for counts/percentages of true values, such as `1` or `True`; and a column for counts/percentages of missing values, such as `numpy.NaN`. Consequently, we might expect the domain to be _external_ to the table. For example:

![Screenshot 2022-05-31 at 17-44-57 Dataset Report](https://user-images.githubusercontent.com/477263/171228840-a0a5d716-9519-4a7f-9e4d-c7ff15a927a2.png)

**How should we name these columns?** We could name them according to:

* the specific encoding: `False`/`True`; or `0`/`1`. However, we might have a dataset that has some boolean variables encoded as `False`/`True` and some as `0`/`1`. Should we distinguish between encodings?
* a generic encoding: false, true. A user could infer the specific encoding by noting that if a boolean variable has an integer type (e.g. `int64`), then it probably encodes false as `0` and true as `1`. Similarly, if a boolean variable has a boolean type (e.g. `bool`), then it probably encodes false as `False` and true as `True`. Should we be explicit?

[^1]: Extracting a feather file will give `False`/`True`; extracting a CSV file will give `0`/`1`. However, users may modify these extracts, to give a dataset that has some boolean variables encoded as `False`/`True` and some as `0`/`1`. Naturally, [that will never happen](https://en.wikipedia.org/wiki/Murphy%27s_law) 😬.

**Comment by Jongmassey** [comment]
>However, we might have a dataset that has some boolean variables encoded as False/True and some as 0/1

What would be the circumstances in which that would happen? I'm very much in favour of providing the _actual_ values in the report rather than translating/standardising truthy/falsey ones as this might trip up people writing code which parses the output of a cohort.

**Comment by iaindillingham** [comment]
> What would be the circumstances in which that would happen?

For example: a researcher extracts a CSV file and transforms it using a scripted action, writing a feather file. Let's say a researcher knows that each integer variable in their study definition is really a boolean variable, so they cast from the former to the latter in the scripted action:

```py
df = pandas.read_csv("output/input.csv")
df = df.select_dtypes(int).astype(bool)
# more transformation
df.to_feather("output/transformed_input.feather")
```

However, if the boolean variables contain missing values, then they won't be `int` (`int64`). They will be `float` (`float64`). That's because `read_csv` will interpret missing values as `numpy.nan`, which is a `float`. So, the boolean variables that contained missing values would be encoded as `0`/`1`, whilst the boolean variables that didn't would be encoded as `False`/`True`.

We could argue that dataset-report should only be used immediately downstream of cohort-extractor. However, that's limiting. What about [cohort-joiner](https://github.com/opensafely-actions/cohort-joiner)?

Ideally, we'd like dataset-report to be quick, easy, and informative. I'm also in favour of providing the actual values. But I also see that having one summary table for each data type, which probably means variable type, is convenient. Maybe the solution is to recognize that boolean variables have two encoding types, and produce a table for each encoding type. Most people should only see one table; if some people see two tables, then they should realize that something's not quite right.

This discussion may seem pedantic. Wait until we get to dates, though 🙂

**Comment by Jongmassey** [comment]
>Maybe the solution is to recognize that boolean variables have two encoding types, and produce a table for each encoding type. Most people should only see one table; if some people see two tables, then they should realize that something's not quite right.

This I like

**Comment by wjchulme** [comment]
> We could argue that dataset-report should only be used immediately downstream of cohort-extractor. However, that's limiting.

I agree this is limiting and ideally should be avoided. I usually do a dataset-report thing on downstream datasets that have been processed in some way, and restricting the report to cohort-extractor outputs only would prevent that.

**Comment by wjchulme** [comment]
> Most people should only see one table; if some people see two tables, then they should realize that something's not quite right

I think that's the right way to think about it. Some yes/nos are encoded as boolean, some as integer. The user should make decisions about which form is correct, so those that are integer should be treated as integer by dataset-report. If the user wants them to be boolean, then they can convert to a boolean (in R and stata, anyway! is there really no `True/False/None` boolean form in pandas??). 

Note that all the "does this pattern exist in this patient's record" variables that are returned by a study definition will never contain missing values, as the pattern is either there is isn't. There is no "unknown". Most boolean variables in OpenSAFELY will be derived this way. Most of the other variables we could naturally think of as boolean will be represented by categorical variables, for example [the symptomatic flag in SGSS](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_test_result_in_sgss--symptomatic). This is all to say that I don't think the issue with `0`/`1`/missing as `float` will be very common.

**Comment by Jongmassey** [comment]
> is there really no True/False/None boolean form in pandas? 

https://pandas.pydata.org/docs/reference/api/pandas.BooleanDtype.html#pandas.BooleanDtype

**Comment by iaindillingham** [comment]
Thanks for the feedback, @robinyjpark, @Jongmassey, and @wjchulme. I've been working on this issue, and have a version of dataset-report that produces a summary table like this:

![Screenshot 2022-06-13 at 17-19-50 Dataset Report](https://user-images.githubusercontent.com/477263/173399333-4a5cb510-5743-49d7-8245-c833abc8a05b.png)

To compare, the current version of dataset-report produces one summary table per variable, [like this](https://opensafely-actions.github.io/dataset-report/input.html).

Notice that I've _not_ treated an integer as an integer; I've retained the logic for treating an integer, with boolean-like characteristics, as a boolean. However, I'd like to focus on the nature of the summary table, rather than the nature of boolean-like characteristics. Specifically:

* to what extent is the summary table skimable? One summary table per data type is clearly more compact than one summary table per variable. But being skimable and being compact aren't the same thing.
* now, the summary table counts values from an external domain, rather than from the internal domain. In the current version of dataset-report, if a variable doesn't have any `0` values, then the variable's summary table doesn't have a `0` row. Now, this isn't the case. The trade-off is that the external domain has to be represented as `float`s rather than `int`s: `NaN`, `0.0`, and `1.0`.[^1] To what extent is this confusing? On the one hand, you're told that a variable is an `int`; on the other hand, you're told that it contains 1,000 instances of `1.0`.

[^1]: I've experimented with the `Int64` data type, which represents the external domain with the correct level of precision: `0`, `1`, and `pandas.NA`. Unfortunately, however, `pandas.NA` isn't compatible with `MultiIndex`, so we can't group column values into "Count" and "Percentage".

**Comment by iaindillingham** [comment]
This has turned out to be a pain, so I've split the work into three units. The first two units have PRs, and will be useful regardless:

* #28 
* #29 

The final unit addresses the substantive issue, and I'd appreciate your feedback:

* #30

**Comment by iaindillingham** [comment]
I'm going to close this issue; see #30 for my rationale. Thank you all for your comments, which have resulted in #28 and #29, at least 🙂.
